"""Generate EXTERNAL_FEEDBACK.md from the claims registry.

A record of the external feedback received and what was done about each point.
Figures come from the registry; commit hashes are checked against git history
by tests/test_all.py. Status words are ours: DONE, PARTIAL, NOT DONE.
"""
from __future__ import annotations
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from verify_claims import registry  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..")
R = registry()


def n(k, fmt="{:.0f}"):
    """Figure plus its claim tag (pipes escaped, see gen_one_sided_doc.n)."""
    v = R[k][0]
    return f"{fmt.format(v)}<!-- claim: {k.replace('|', chr(92) + '|')} = {v:.4f} -->"


def main():
    L = []
    A = L.append
    A("# External feedback, and what was done about it\n")
    A("> **Generated by `src/gen_feedback_doc.py`; figures are registry-checked "
      "by `src/verify_claims.py`. Commit hashes are checked against git history "
      "by the test suite.** Statuses are ours and are conservative: DONE means "
      "the fix is on the public `main` branch; PARTIAL and NOT DONE are listed "
      "as plainly as DONE.\n")
    A("Two external conversations this week produced concrete feedback. Both "
      "were transcribed by speech-to-text, and both transcripts "
      "are garbled in places. Where a point could be read more than one way, "
      "this document says so instead of choosing the reading that flatters "
      "us. The transcripts themselves are not published here.\n")

    A("## Summary\n")
    A("| # | Source | Point | Status |")
    A("|---|---|---|---|")
    rows = [
        ("M1", "ML engineer", "An IP address or log left in a markdown file",
         "PARTIAL: removed from current files; still in git history"),
        ("M2", "ML engineer", "Inconsistent verdicts across repeated identical runs",
         "PARTIAL: not reproduced; one real seed-dependence found and fixed"),
        ("M3", "ML engineer", "Refusal line stated as 85%, measured near 95.1%",
         "PARTIAL: reconciled in the docs; the 85% threshold itself is unchanged"),
        ("M4", "ML engineer", "Try Qwen3.5",
         "PARTIAL: published-card ingestion done; GPU testing not run"),
        ("M5", "ML engineer", "Distillation, enterprise nuance, other remarks",
         "NOT DONE"),
        ("C1", "Collaborator", "README is overwhelming as an entry point", "DONE"),
        ("C2", "Collaborator", "Another metric or benchmark would help", "NOT DONE"),
        ("C3", "Collaborator", "Too small to sell alone; fits inside a suite",
         "PARTIAL: two integration paths scoped, nothing built"),
        ("C4", "Collaborator", "Fastest willingness-to-pay signal",
         "NOT DONE (form field drafted, then declined)"),
    ]
    for r in rows:
        A("| " + " | ".join(r) + " |")
    A("")

    A("## External ML engineer\n")
    A("The external ML engineer tested the tool against internal models of "
      "their own organization and gave feedback on a call. We do not have those "
      "models or inputs, so everything the ML engineer ran remains unreproduced on our "
      "side.\n")

    A("### M1. An IP address or log in a markdown file\n")
    A("**What was said:** \"one of her IP logs is on the [markdown] file, so "
      "make sure to scrap this.\" The transcript is garbled; we read it as an "
      "IP address or log excerpt left in a `.md` file.\n")
    A("**What we found:** one address, belonging to a cloud GPU instance that "
      "has since been terminated, in `KURTOSIS_LORA_FINDINGS.md`. It was "
      "removed from that file in `cef5eff`. We do not know whether it is the "
      "item the ML engineer meant, since the transcript does not name the file.\n")
    A("**What is not fixed:** the address is still present in three earlier "
      "commits on `main` (`077da61`, `99f1ca5`, `37364d2`) and in one "
      "orphaned commit that is no longer on any branch but can still be "
      "fetched by its hash. We did not rewrite history: "
      "the instance no longer exists, and a rewrite would change every "
      "published hash. That is a judgement call, and it is open.\n")

    A("### M2. Inconsistent verdicts on repeated identical runs\n")
    A("**What was said:** verdicts \"were kind of inconsistent while running "
      "with the same exact thing, multiple iterations.\"\n")
    A("**What we found:** running the tool repeatedly on the same input in "
      "the same environment gave identical output, across different hash "
      "seeds and in-process orderings. We could not reproduce the symptom. "
      "We did find a real source of run-to-run variation nearby: the "
      "checkpoint-level bootstrap bounds for cells with very few checkpoints "
      "depended on the random seed, by up to five percentage points, so "
      "regenerating the coverage file under a different seed could flip a "
      "cell's verdict. The verdict logic now uses an exact enumeration for "
      "small cluster counts (`16693a2`), with a test that the bounds do not "
      "depend on the random stream.\n")
    A("**What is open:** we do not know that this is what the ML engineer saw. Their "
      "runs used internal models that are not in our data, and we never "
      "obtained the inputs. The fix removes a real nondeterminism; it does "
      "not close the report. Reproduction needs the exact command, the input "
      "files and the library versions.\n")

    A("### M3. Refusal line at 85%, measured closer to 95.1%\n")
    A("**What was said:** the 85% refusal line \"is slightly higher than "
      "that,\" around 95.1 in their experiments. It is unclear from the "
      "transcript what quantity that 95.1 measures.\n")
    A(f"**What we found:** the refusal threshold is {n('refuse_below_pct')}% "
      f"and is stated as such. Separately, pooled one-sided coverage of the "
      f"interval is {n('pooled_one_sided_pct', '{:.1f}')}%, which is the "
      "interval's real one-sided nominal level, since a symmetric interval "
      "advertised at 90% splits its 10% across two tails. That matches the "
      "number the ML engineer gave, but we cannot confirm it is the same quantity. "
      "That the nominal one-sided level is about 95% was already stated "
      "in the docs (`fd682b2`, derivation in `ONE_SIDED_COVERAGE.md`) "
      "before this feedback arrived, so that part is not a response to it. "
      "What was done afterwards is a sweep for stale statements of the "
      "refusal behaviour in the docs, paper and messages (`a31a1f7`), which "
      "also changed the refusal message: it had compared coverage against "
      "the 90% the interval claims, and now cites the refusal threshold and "
      "the one-sided level.\n")
    A("**What is open:** whether 85% is the right refusal line has not been "
      "revisited. It is a design choice we have not re-derived, and the engineer's "
      "comment may be an argument for moving it.\n")

    A("### M4. Try it on Qwen3.5\n")
    A("**What was said:** Qwen3.5 is a good architecture to stress, because "
      "its distillation differs from other families, and \"you don't need to "
      "spend money\" if that is not practical. The transcript renders the "
      "model version inconsistently; we took it to mean Qwen3.5.\n")
    A(f"**Done:** the free half. Published quantized Qwen3.5 cards were "
      f"ingested through the unchanged card parser (`33da3b6`): "
      f"{n('qwen35_pub_rows')} rows kept, {n('qwen35_pub_verified')} of them "
      f"passing the recovery check, from {n('qwen35_pub_repos')} repos, and "
      f"{n('qwen35_pub_rejects')} rejected. They live in `data/qwen35/`, "
      "separate from the corpus, whose contents are unchanged. Results are "
      "in `out/qwen35_published_summary.json`; they rest on two dense "
      "checkpoints per scheme and should be read that way.\n")
    A(f"**Not done:** the adversarial GPU sweep on Qwen3.5. It needs a paid "
      f"GPU run that has not been approved, and the pipeline has not been "
      f"adapted to Qwen3.5's hybrid attention layers. For context, the "
      f"existing sweep covers {n('adv_models')} base models, all Qwen2.5, "
      f"at {n('adv_min_params_b', '{:.3f}')}B, {n('adv_mid_params_b', '{:.1f}')}B and "
      f"{n('adv_max_params_b', '{:.1f}')}B parameters.\n")
    A("**Owed:** a correction to the ML engineer. The sweep was described on the call "
      "as covering roughly 0.5B to 8B parameters; it covers only the three "
      "sizes above. That correction has not been sent.\n")

    A("### M5. Other remarks\n")
    A("- **Enterprise nuance:** asked whether built-in refusal matters to "
      "enterprises, the answer was that it is \"a lot more nuanced.\" No "
      "specifics were given, so there is nothing to act on yet.\n")
    A("- **Distillation:** the ML engineer said they saw less of a difference on "
      "distilled local models. The corpus contains no distilled-model data, "
      "and what difference was meant is unclear. Not addressed.\n")
    A("- **Follow-ups we owe:** ask how the internal models were run and on "
      "what inputs (which M2 depends on), what the 95.1 measures, and which "
      "file held the address.\n")
    A("- A remark about a fallback pattern was mentioned in the "
      "request for this document; it does not appear in the transcript we "
      "have, so we cannot say whether it was missed.\n")

    A("## External technical collaborator\n")
    A("The external technical collaborator gave feedback on a call as a reviewer who "
      "works on document-processing workflows and does consulting, by their "
      "own account.\n")

    A("### C1. The README is overwhelming as an entry point\n")
    A("**What was said:** the README is well written, but \"links to a lot "
      "of files,\" so it is \"a little hard to know where to get started.\"\n")
    A("**What was done:** a first-screen block with a one-minute path "
      "(clone, install, two example commands) and a short statement of what "
      "the tool is and is not, ahead of all existing links (`00d5d18`), with "
      "stale refusal text corrected (`8fbe7e5`). No documentation was "
      "removed. The rendering was checked on the live github.com page, not "
      "only locally. One correction: the block first said the first run takes "
      "about half a minute. That was a one-time cold-import cost in a fresh "
      "environment on one machine, not the tool's runtime, and it has since "
      "been reworded.\n")

    A("### C2. Another metric or benchmark\n")
    A("**What was said:** the methodology looked sound, but it \"would be "
      "nice to have another metric.\" The collaborator also dated BenchPress ten years "
      "earlier than our citation does.\n")
    A("**What we did:** nothing on the metric; no second benchmark was "
      "added. On the date: the citation gives 2026 and arXiv identifier "
      "2606.24020, whose prefix encodes June 2026, so we think the "
      "earlier date was a slip, but we did not ask.\n")

    A("### C3. Too small to sell alone; a suite is the natural home\n")
    A("**What was said:** \"too small to be a product\" alone; it would need "
      "to sit in a larger suite of the MLflow or Weights & Biases kind, or "
      "serve as a Python package or as a free tool that leads to consulting.\n")
    A("**What was done:** research-only scoping of an MLflow integration, "
      "and of the packaging refactor that a `pip install` would need. "
      "Neither was built, and neither is committed to this repo; both are "
      "waiting on a decision.\n")

    A("### C4. Willingness to pay\n")
    A("**What was said:** the fastest signal would come through academic "
      "connections, and a sale within a week is \"pretty ambitious\"; "
      "enterprise deals take months.\n")
    A("**What was done:** an optional willingness-to-pay question for the "
      "feedback form was drafted in a local commit that was never "
      "pushed. It was **not** added: the decision was not to ask. The live "
      "form has no such field. No academic-outreach plan has been made.\n")

    A("## Not addressed\n")
    A("- The history copies of the address (M1).\n")
    A("- The ML-engineer reproduction, pending their inputs (M2).\n")
    A("- Whether the 85% refusal line should move (M3).\n")
    A("- The Qwen3.5 GPU sweep (M4) and the correction owed to the ML engineer.\n")
    A("- Distillation and the other remarks (M5).\n")
    A("- A second metric (C2), and any willingness-to-pay measurement (C4).\n")
    A(f"- Current tool state, for reference: {n('n_cells_total')} cells, "
      f"{n('n_cells_refused')} refused, "
      f"{n('n_cells_insufficient_evidence')} at insufficient evidence "
      f"(fewer than {n('min_cell_checkpoints')} checkpoints or an "
      "inconclusive bootstrap).\n")

    out = os.path.join(ROOT, "EXTERNAL_FEEDBACK.md")
    with open(out, "w") as f:
        f.write("\n".join(L))
    print("wrote", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
