"""
Generate RANKING.md from computed values.

The standing rule is that no quantitative claim may be written in prose without
a number that traces to a computation. The strongest form of that rule is to
stop hand-writing the document: every figure below is pulled from
verify_claims.registry() and emitted with a `<!-- claim: key = value -->` tag
that src/verify_claims.py re-checks.

Run:  python src/gen_ranking_doc.py && python src/verify_claims.py
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from verify_claims import registry  # noqa: E402
import rank as R  # noqa: E402

HERE = os.path.dirname(__file__)
DOC = os.path.join(HERE, "..", "RANKING.md")
REG = registry()


def esc(cell):
    """Cell names contain a pipe, which would break the markdown table."""
    return cell.replace("|", r"\|")


def v(key):
    return REG[key][0]


def n(key, fmt="{:.0f}"):
    """Emit a number together with the tag that lets it be re-verified.

    The pipe in a key such as `cell_rows::w4a16|<2B` is escaped: GFM treats an
    unescaped pipe as a column delimiter anywhere in a table row, including
    inside an HTML comment, so leaving it raw splits the row and prints the tag
    as visible text on github.com. python-markdown is permissive, so a local
    render gives no warning. The claim parsers unescape it on read.
    """
    val = v(key)
    safe = key.replace("|", chr(92) + "|")
    return f"{fmt.format(val)}<!-- claim: {safe} = {val:.4f} -->"


def main():
    L = []
    A = L.append

    A("# Scheme ranking\n")
    A("```bash")
    A("python src/rank.py w4a16 fp8 nvfp4 w8a8 --size 1.5B")
    A("```\n")
    A("Ranks quantization schemes. Inputs read: the scheme name, and "
      "optionally a model size band.")
    A(f"Nothing else about your model is read. The fitted predictor is "
      f"{n('n_numbers_in_predictor')} numbers: 6 scheme means, 6 scheme "
      f"half-widths, and {n('n_size_dependent_widths')} size-dependent "
      f"widths.\n")
    A(f"Built on {n('n_rows')} published evaluations from "
      f"{n('n_checkpoints')} checkpoints across {n('n_families')} model "
      f"families. "
      f"Of the {n('n_rows_raw')} rows extracted, "
      f"{n('n_rows_dropped_near_chance')} with a baseline below "
      f"{n('min_acc_before_pct')}% accuracy (near chance) are dropped.\n")
    A("> **Every number in this file is generated by `src/gen_ranking_doc.py` "
      "from computed values and\n"
      "> re-checked by `src/verify_claims.py`. Do not hand-edit figures here; "
      "regenerate instead.**\n")
    A("---\n")

    # ---------------------------------------------------------------- Part 1
    A("## Part 1 — size stratification (SCOPE.md item #4)\n")
    A("### The size effect is real\n")
    A("| scheme | <2B | 2–10B | >10B |")
    A("|---|---|---|---|")
    A(f"| W4A16 mean | {n('w4a16_mean::<2B', '{:+.2f}')}pp | "
      f"{n('w4a16_mean::2-10B', '{:+.2f}')}pp | "
      f"{n('w4a16_mean::>10B', '{:+.2f}')}pp |")
    A(f"| W4A16 5th pct | {n('w4a16_p05::<2B', '{:+.2f}')}pp | "
      f"{n('w4a16_p05::2-10B', '{:+.2f}')}pp | "
      f"{n('w4a16_p05::>10B', '{:+.2f}')}pp |")
    A(f"| near-lossless mean | {n('lossless_mean::<2B', '{:+.2f}')}pp | "
      f"{n('lossless_mean::2-10B', '{:+.2f}')}pp | "
      f"{n('lossless_mean::>10B', '{:+.2f}')}pp |\n")
    A("W4A16 damage varies with size; near-lossless schemes do not.\n")

    A("### Full stratification was tested and rejected\n")
    A("Per-(scheme, size band) intervals narrowed the >10B band and "
      "prospective coverage fell from 90.3% to 84.4%. Those two figures come "
      "from `src/validate_strata.py`, which is a separate run rather than "
      "part of this registry. What shipped instead is one-sided: a size cell "
      "may only *widen* the scheme interval, never narrow it.\n")
    A(f"Under strict held-out calibration the widening applies to "
      f"{n('widening_share_pct', '{:.0f}')}% of evaluations (row-by-calibration-family), and where it "
      f"applies coverage is {n('widening_coverage_pct', '{:.1f}')}%. It is "
      f"a safety margin on a minority of queries, not a reshaping of the "
      f"envelope.\n")

    A("### Cells too thin to stand alone\n")
    A("| cell | training rows | checkpoints |")
    A("|---|---|---|")
    for key in sorted(k for k in REG if k.startswith("cell_train_rows::")):
        cell = key.split("::", 1)[1]
        A(f"| `{esc(cell)}` | {n(key)} | "
          f"{n('cell_train_ckpt::' + cell)} |")
    A("")
    A(f"MoE support is {n('moe_rows')} rows from {n('moe_checkpoints')} "
      f"checkpoints, all Mixtral, which is why MoE is carried as a flag "
      f"rather than its own interval.\n")
    A("---\n")

    # ---------------------------------------------------------------- Part 2
    A("## Part 2 — the ranking\n")
    A("### Criteria\n")
    A(f"**1. Interval width.** Primary sort within a tier. Narrower means the "
      f"historical spread is tighter.\n")
    A(f"**2. Tail risk as a rate.** Thresholding on the single worst "
      f"observation flagged 5 of 6 schemes, because the worst value grows "
      f"with sample size. The flag uses the share of evaluations losing more "
      f"than 3pp, threshold {n('severe_rate_threshold_pct')}%.\n")
    A(f"**3. Support.** `THIN_DATA` fires below {n('thin_rows_threshold')} "
      f"evaluations or {n('thin_families_threshold')} model families.\n")

    A("### Per-scheme figures\n")
    A("| scheme | interval | worst observed | % losing >3pp | evals | ckpts | "
      "families | held-out coverage at or above the lower bound (checkpoint-bootstrap 90%) |")
    A("|---|---|---|---|---|---|---|---|")
    order = sorted((k for k in REG if k.startswith("lo::")),
                   key=lambda k: v(k.replace("lo::", "hi::")) - v(k))
    for key in order:
        s = key.split("::", 1)[1]
        A(f"| {s} | [{n('lo::' + s, '{:+.2f}')}, "
          f"{n('hi::' + s, '{:+.2f}')}] | "
          f"{n('worst::' + s, '{:+.2f}')}pp | "
          f"{n('severe_pct::' + s, '{:.1f}')}% | {n('n::' + s)} | "
          f"{n('checkpoints::' + s)} | {n('families::' + s)} | "
          f"{n('scheme_cov_one::' + s, '{:.1f}')}% "
          f"[{n('scheme_boot_lo::' + s, '{:.1f}')}, "
          f"{n('scheme_boot_hi::' + s, '{:.1f}')}] |")
    A("")

    A("### Tiers\n")
    A("| tier | rule |")
    A("|---|---|")
    A(f"| A | no flag triggered |")
    A(f"| B | one or more non-severe flags |")
    A(f"| C | severe-loss rate above "
      f"{n('severe_rate_threshold_pct')}%, or coverage not established at "
      f"{n('poor_coverage_threshold_pct')}% (fewer than "
      f"{n('min_cell_checkpoints')} checkpoints, or the checkpoint-bootstrap "
      f"interval reaches below the line), or insufficient calibration |\n")
    A("Tier labels state the rule that produced them. They are not safety "
      "judgements: the worst observed loss is printed for every scheme at "
      "every tier and rank.\n")

    A("### Measured coverage per cell\n")
    A("Strict protocol: the test family is unseen and the calibration family "
      "is a different unseen family.\n")
    A(f"Pooled: {n('pooled_cell_coverage_pct', '{:.1f}')}% across all "
      f"{n('pooled_distinct_rows')} rows, each scored under "
      f"{n('pooled_pairs_per_row')} different calibration families "
      f"({n('pooled_scored_pairs')} evaluations, which are not independent "
      f"rows), against 90% claimed.\n")
    A(f"Every scheme, and every size cell, is judged the same way: one-sided "
      f"coverage, uncertainty from a bootstrap that resamples whole "
      f"checkpoints, and a state of insufficient evidence when there are "
      f"fewer than {n('min_cell_checkpoints')} checkpoints or the "
      f"bootstrap 90% interval straddles the {n('refuse_below_pct')}% line. "
      f"Across all sizes, {n('n_schemes_insufficient_evidence')} of 6 schemes "
      f"are in that state and {n('n_schemes_refused')} are refused.\n")
    A("Two coverage figures are given. **One-sided** is how often the true "
      "result stayed at or above the interval's lower bound, and it is what "
      "the verdict is scored on: the risk being bounded is accuracy loss, so "
      "a model that beats its envelope has not failed anyone. **Two-sided** "
      "is plain containment, shown for context. See `ONE_SIDED_COVERAGE.md`.\n")
    A("| cell | rows | checkpoints | one-sided (verdict) | two-sided |")
    A("|---|---|---|---|---|")
    cells = sorted((k for k in REG if k.startswith("cell_coverage_pct::")),
                   key=v)
    for key in cells:
        cell = key.split("::", 1)[1]
        osk = f"cell_one_sided_pct::{cell}"
        judged = v(osk) if osk in REG else v(key)
        ckk = f"cell_ckpts::{cell}"
        # the verdict is the tool's own (rank.classify_cell), never re-derived here
        state = R.classify_cell({
            "distinct_checkpoints": v(ckk) if ckk in REG else None,
            "coverage_one_sided": judged / 100,
            "boot90_lo": v(f"cell_boot_lo::{cell}"), "boot90_hi": v(f"cell_boot_hi::{cell}")})
        mark = {"trusted": "", "insufficient_evidence": " *insufficient evidence*",
                "refused": " **refused**"}[state]
        one = n(osk, "{:.1f}") + "%" if osk in REG else "n/a"
        A(f"| `{esc(cell)}` | {n('cell_rows::' + cell)} | "
          f"{n(ckk) if ckk in REG else '?'} | {one}{mark} | "
          f"{n(key, '{:.1f}')}% |")
    A("")
    A("| size band | coverage |")
    A("|---|---|")
    for b in ("<2B", "2-10B", ">10B"):
        k = f"band_coverage_pct::{b}"
        if k in REG:
            A(f"| {b} | {n(k, '{:.1f}')}% |")
    A("")
    A(f"Two cells were originally flagged for falling below the "
      f"{n('poor_coverage_threshold_pct')}% threshold. Under the three-state "
      f"rule neither is a confident refusal: both are `insufficient_evidence`. "
      f"For an `insufficient_evidence` cell the tool still prints the "
      f"all-sizes interval, but demotes the scheme to Tier C and says the "
      f"cell cannot be judged; only a `refused` cell has its interval "
      f"withheld (`INSUFFICIENT CALIBRATION`), and none currently is. "
      f"The checkpoint floor is checked before anything else, so a cell "
      f"with one checkpoint (such as `fp8\\|<2B`, "
      f"{n('cell_rows::fp8|<2B')} rows) is insufficient evidence whatever its "
      f"row count; an earlier ordering let it through as trusted. "
      f"Neither flagged cell can be fixed with current data: "
      f"`w4a16\\|<2B` has {n('cell_train_rows::w4a16|<2B')} training rows from "
      f"{n('cell_train_ckpt::w4a16|<2B')} checkpoints, and the widening that "
      f"would fix `w8a16\\|>10B` needs 9+ calibration rows and rarely gets "
      f"them.\n")
    A("### Training support floor\n")
    A(f"Measured coverage alone cannot earn Tier A. A size cell must also "
      f"rest on at least {n('min_cell_checkpoints')} distinct checkpoints, "
      f"because rows from one checkpoint across many benchmarks are "
      f"correlated views of a single quantization run rather than "
      f"independent evidence.\n")
    A(f"{n('n_cells_blocked_from_tier_a')} cells fall below that floor:\n")
    A("| cell | training rows | checkpoints | measured coverage | Tier A? |")
    A("|---|---|---|---|---|")
    keys = sorted(k.split("::", 1)[1] for k in REG
                  if k.startswith("cell_train_ckpt2::"))
    for cell in keys:
        ck = v(f"cell_train_ckpt2::{cell}")
        if ck >= v("min_cell_checkpoints"):
            continue
        covk = f"cell_coverage_pct::{cell}"
        cov = n(covk, "{:.1f}") + "%" if covk in REG else "n/a"
        A(f"| `{esc(cell)}` | {n('cell_train_rows2::' + cell)} | "
          f"{n('cell_train_ckpt2::' + cell)} | {cov} | blocked |")
    A("")
    A("Three of these have excellent measured coverage. That is the point: "
      "high coverage on one checkpoint is not evidence that the interval "
      "generalises, only that it fitted one model.\n")
    A("---\n")

    A("## What this cannot do\n")
    A(f"- {n('intervals_excluding_zero')} of 6 intervals exclude zero, so it "
      f"cannot say a scheme will definitely cost accuracy.")
    A(f"- {n('n_big_losses_below_floor')} of {n('n_big_losses')} observed "
      f"losses worse than 3pp fell below their interval floor.")
    A(f"- It is built on checkpoints Red Hat chose to publish, so damage from "
      f"an untuned recipe is not represented.")
    A(f"- It reads 2 inputs. A 1B and a 70B model of the same scheme differ "
      f"only through {n('n_size_dependent_widths')} size-dependent widths.\n")

    open(DOC, "w").write("\n".join(L) + "\n")
    print(f"wrote {DOC} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
