"""Generate ONE_SIDED_COVERAGE.md from the claims registry."""
from __future__ import annotations
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from verify_claims import registry  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..")
R = registry()


def n(k, fmt="{:.0f}"):
    v = R[k][0]
    return f"{fmt.format(v)}<!-- claim: {k} = {v:.4f} -->"


W8, W4 = "w8a16|>10B", "w4a16|<2B"


def esc(cell):
    """Escape the pipe for a markdown TABLE cell.

    GitHub Flavored Markdown treats an unescaped pipe as a column delimiter
    even inside a code span, so `w4a16|<2B` silently splits the row on
    github.com. python-markdown is more forgiving, which is why this does not
    show up in the local PDF render.
    """
    return cell.replace("|", "\\|")


def main():
    L = []
    A = L.append
    A("# One-sided coverage: two refusals that are not the same event\n")
    A("> **Generated by `src/gen_one_sided_doc.py` from computed values and "
      "re-checked by `src/verify_claims.py`. Do not hand-edit figures.**\n")
    A("## Where this came from\n")
    A("A reader on Reddit re-ran `src/cell_coverage.py` against the committed "
      "artifact, reproduced our numbers, and then argued that the two cells "
      "the tool refuses are failing for different reasons and should not be "
      "scored the same way. They were right. This records their finding, how "
      "it was verified, and what it changes.\n")
    A("They also pointed out an inconsistency in our own code: the comment in "
      "`cell_coverage.py` says the checkpoint is the honest unit of evidence, "
      "and that standard is enforced on *training support* via the "
      "three-checkpoint floor -- but not on the coverage figure that drives "
      "the refusal itself. That was accurate and is now fixed.\n")

    A("## What they claimed, and what we measured\n")
    A("Every figure below was recomputed from `data/dataset.csv` by "
      "`src/one_sided_audit.py`, which rebuilds the leave-family-out scored "
      "rows and retains the interval bounds the committed artifact does not "
      "store. Nothing was taken from their summary.\n")
    A("| check | they claimed | we computed | verdict |")
    A("|---|---|---|---|")
    A(f"| pooled coverage | 91.0% / 5719 | {n('os_pooled_pct','{:.1f}')}% / "
      f"{n('os_pooled_rows')} | matches |")
    A(f"| `{esc(W8)}` two-sided | 73.7% / 217 | {n('os_two_sided_pct::'+W8,'{:.1f}')}% "
      f"/ {n('os_scored_rows::'+W8)} | matches |")
    A(f"| `{esc(W4)}` two-sided | 68.8% / 77 | {n('os_two_sided_pct::'+W4,'{:.1f}')}% "
      f"/ {n('os_scored_rows::'+W4)} | matches |")
    A(f"| `{esc(W8)}` checkpoints | 5 | {n('os_distinct_checkpoints::'+W8)} | matches |")
    A(f"| `{esc(W8)}` distinct (model, benchmark) | 31 | "
      f"{n('os_distinct_model_benchmark::'+W8)} | matches |")
    A(f"| `{esc(W4)}` checkpoints | 2 | {n('os_distinct_checkpoints::'+W4)} | matches |")
    A(f"| `{esc(W4)}` distinct rows | 11 | {n('os_distinct_model_benchmark::'+W4)} "
      f"| matches |")
    A(f"| `{esc(W8)}` one-sided | 81.1% | {n('os_one_sided_pct::'+W8,'{:.1f}')}% | matches |")
    A(f"| `{esc(W4)}` below lower bound | 29.9% | {n('os_below_lo_pct::'+W4,'{:.1f}')}% "
      f"| matches |")
    A(f"| `{esc(W8)}` cluster 90% interval | [46%, 98%] | "
      f"[{n('os_boot90_lo::'+W8,'{:.0f}')}%, {n('os_boot90_hi::'+W8,'{:.0f}')}%] "
      f"| matches |")
    A("")

    A("### Per-checkpoint coverage, verified against raw data\n")
    A(f"| checkpoint | measured |")
    A("|---|---|")
    for k in sorted(k for k in R if k.startswith(f"os_ckpt::{W8}::")):
        A(f"| `{k.split('::')[-1]}` | {n(k,'{:.1f}')}% |")
    A("")

    A("### One description of theirs that did not verify\n")
    A("They wrote that every 405B miss is above the upper bound *\"(mean delta "
      "+0.27pp)\"* and every 70B miss below the lower bound *\"(mean -1.52pp)\"*. "
      "The directional split is exactly right. The two means are not the mean "
      "delta **of the misses** -- those are "
      f"{n('os_missmean::'+W8+'::Meta-Llama-3.1-405B-Instruct','{:+.2f}')}pp and "
      f"{n('os_missmean::'+W8+'::Meta-Llama-3.1-70B-Instruct','{:+.2f}')}pp -- they are the "
      "mean delta across **all** rows for each checkpoint. Their arithmetic is "
      "correct; the phrasing points at the wrong subset. It does not affect "
      "the conclusion.\n")

    A("## The conclusion\n")
    A(f"**`{W4}` is an earned refusal.** "
      f"{n('os_below_lo_pct::'+W4,'{:.1f}')}% of its rows fall below the lower "
      f"bound and only {n('os_above_hi_pct::'+W4,'{:.1f}')}% above the upper "
      f"one, so scoring it one-sided barely moves it: "
      f"{n('os_two_sided_pct::'+W4,'{:.1f}')}% to "
      f"{n('os_one_sided_pct::'+W4,'{:.1f}')}%. The damage is real and on the "
      f"side that matters.\n")
    A(f"But the evidence is narrower than the label. Those "
      f"{n('os_scored_rows::'+W4)} rows are "
      f"{n('os_distinct_model_benchmark::'+W4)} distinct (model, benchmark) "
      f"results from {n('os_distinct_checkpoints::'+W4)} checkpoints in "
      f"{n('os_distinct_families::'+W4)} family. **The claim the data supports "
      f"is about small Qwen, not about every model under 2B.**\n")
    A(f"**`{W8}` is substantially a scoring artefact.** "
      f"{n('os_above_hi_pct::'+W8,'{:.1f}')}% of its rows sit *above* the upper "
      f"bound -- the model beat the envelope, which is not a risk anyone needs "
      f"protecting from. Counting only losses below the lower bound moves it "
      f"from {n('os_two_sided_pct::'+W8,'{:.1f}')}% to "
      f"{n('os_one_sided_pct::'+W8,'{:.1f}')}%, close to the 90% it claims.\n")
    A("What remains after that is one checkpoint. Resampling whole checkpoints "
      f"puts a 90% interval of [{n('os_boot90_lo::'+W8,'{:.0f}')}%, "
      f"{n('os_boot90_hi::'+W8,'{:.0f}')}%] around the headline figure. That "
      f"span cannot distinguish *this cell is uncalibrated* from *one Llama "
      f"checkpoint is an outlier*. By contrast `{W4}` resamples to "
      f"[{n('os_boot90_lo::'+W4,'{:.0f}')}%, {n('os_boot90_hi::'+W4,'{:.0f}')}%] "
      f"-- the earned refusal is also the better-evidenced one.\n")

    A("## What has changed, and what has not\n")
    A("**Done.** Every coverage figure now reports the number of distinct "
      "checkpoints and families beside it, in the JSON artifact and in the "
      "tool's own output. The same standard already applied to training "
      "support now applies to coverage.\n")
    A("**Not done, deliberately.** The refusal threshold still uses two-sided "
      "coverage. Switching it would likely stop refusing "
      f"`{W8}`, which changes a published headline and propagates to the "
      "one-page summary, the ranking document and the paper. That is a "
      "decision to take deliberately, not a side effect of a bug fix.\n")
    A("## Open question\n")
    A(f"A cell resting on {n('os_distinct_checkpoints::'+W4)} checkpoints and "
      f"one resting on {n('os_distinct_checkpoints::'+W8)} are currently "
      "treated as the same kind of evidence, and the tool has only two states: "
      "answer, or refuse. Neither fits a cell where the honest position is "
      "*there is not enough evidence to judge*. Whether to add that third "
      "state is an open design question, recorded here rather than resolved "
      "quietly.\n")
    A("## Credit\n")
    A("This finding came from outside the project, from a reader who did the "
      "work: re-ran the code, reproduced the artifact, went to the raw rows, "
      "and identified a real inconsistency between what our own comment said "
      "and what the refusal logic did. It is the first external technical "
      "contribution the project has received, and it improved it.\n")
    open(os.path.join(ROOT, "ONE_SIDED_COVERAGE.md"), "w").write("\n".join(L) + "\n")
    print("wrote ONE_SIDED_COVERAGE.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
