"""Generate ONE_SIDED_COVERAGE.md from the claims registry."""
from __future__ import annotations
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from verify_claims import registry  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..")
R = registry()


def n(k, fmt="{:.0f}"):
    """Figure plus its claim tag.

    The pipe is escaped inside the tag as well as in visible text: GFM treats
    an unescaped pipe as a column delimiter anywhere in a table row, including
    inside an HTML comment, which splits the row and exposes the raw tag on
    github.com. The claim parsers unescape it.
    """
    v = R[k][0]
    return f"{fmt.format(v)}<!-- claim: {k.replace('|', chr(92) + '|')} = {v:.4f} -->"


W8, W4 = "w8a16|>10B", "w4a16|<2B"


def esc(cell):
    """Escape the pipe for a markdown TABLE cell.

    GitHub Flavored Markdown treats an unescaped pipe as a column delimiter
    even inside a code span, so `w4a16|<2B` silently splits the row on
    github.com. python-markdown is more forgiving, which is why this does not
    show up in the local PDF render.
    """
    return cell.replace("|", "\\|")


def main():
    L = []
    A = L.append
    A("# One-sided coverage: two refusals that are not the same event\n")
    A("> **Generated by `src/gen_one_sided_doc.py` from computed values and "
      "re-checked by `src/verify_claims.py`. Do not hand-edit figures.**\n")
    A("## Where this came from\n")
    A("A commenter on Reddit re-ran `src/cell_coverage.py` against the "
      "committed artifact, reproduced our numbers, and then argued that the "
      "two cells the tool refuses are failing for different reasons and "
      "should not be scored the same way. They were right. This records "
      "their finding, how it was verified, and what it changes.\n")
    A("The commenter has identified themselves as an AI account "
      "collaborating with the OpenLanguageModel maintainers, disclosed in "
      "their bio. Their contribution is credited on that basis below, not "
      "as a human reviewer.\n")
    A("They also pointed out an inconsistency in our own code: the comment in "
      "`cell_coverage.py` says the checkpoint is the honest unit of evidence, "
      "and that standard is enforced on *training support* via the "
      "three-checkpoint floor -- but not on the coverage figure that drives "
      "the refusal itself. That was accurate and is now fixed.\n")
    A("They followed up with a second, separate proposal: apply that same "
      "three-checkpoint floor to the coverage *judgment* itself, and treat a "
      "checkpoint-cluster bootstrap interval that straddles the refusal "
      "line the same way. Both parts were independently verified against "
      "the code and data before being implemented; see the sections below.\n")

    A("## What they claimed, and what we measured\n")
    A("Every figure below was recomputed from `data/dataset.csv` by "
      "`src/one_sided_audit.py`, which rebuilds the leave-family-out scored "
      "rows and retains the interval bounds the committed artifact does not "
      "store. Nothing was taken from their summary.\n")
    A("| check | they claimed | we computed | verdict |")
    A("|---|---|---|---|")
    A(f"| pooled coverage | 91.0% / 5719 | {n('os_pooled_pct','{:.1f}')}% / "
      f"{n('os_pooled_rows')} | matches |")
    A(f"| `{esc(W8)}` two-sided | 73.7% / 217 | {n('os_two_sided_pct::'+W8,'{:.1f}')}% "
      f"/ {n('os_scored_rows::'+W8)} | matches |")
    A(f"| `{esc(W4)}` two-sided | 68.8% / 77 | {n('os_two_sided_pct::'+W4,'{:.1f}')}% "
      f"/ {n('os_scored_rows::'+W4)} | matches |")
    A(f"| `{esc(W8)}` checkpoints | 5 | {n('os_distinct_checkpoints::'+W8)} | matches |")
    A(f"| `{esc(W8)}` distinct (model, benchmark) | 31 | "
      f"{n('os_distinct_model_benchmark::'+W8)} | matches |")
    A(f"| `{esc(W4)}` checkpoints | 2 | {n('os_distinct_checkpoints::'+W4)} | matches |")
    A(f"| `{esc(W4)}` distinct rows | 11 | {n('os_distinct_model_benchmark::'+W4)} "
      f"| matches |")
    A(f"| `{esc(W8)}` one-sided | 81.1% | {n('os_one_sided_pct::'+W8,'{:.1f}')}% | matches |")
    A(f"| `{esc(W4)}` below lower bound | 29.9% | {n('os_below_lo_pct::'+W4,'{:.1f}')}% "
      f"| matches |")
    A(f"| `{esc(W8)}` cluster 90% interval | [46%, 98%] | "
      f"[{n('os_boot90_lo::'+W8,'{:.0f}')}%, {n('os_boot90_hi::'+W8,'{:.0f}')}%] "
      f"| matches |")
    A("")

    A("### Per-checkpoint coverage, verified against raw data\n")
    A(f"| checkpoint | measured |")
    A("|---|---|")
    for k in sorted(k for k in R if k.startswith(f"os_ckpt::{W8}::")):
        A(f"| `{k.split('::')[-1]}` | {n(k,'{:.1f}')}% |")
    A("")

    A("### One description of theirs that did not verify\n")
    A("They wrote that every 405B miss is above the upper bound *\"(mean delta "
      "+0.27pp)\"* and every 70B miss below the lower bound *\"(mean -1.52pp)\"*. "
      "The directional split is exactly right. The two means are not the mean "
      "delta **of the misses** -- those are "
      f"{n('os_missmean::'+W8+'::Meta-Llama-3.1-405B-Instruct','{:+.2f}')}pp and "
      f"{n('os_missmean::'+W8+'::Meta-Llama-3.1-70B-Instruct','{:+.2f}')}pp -- they are the "
      "mean delta across **all** rows for each checkpoint. Their arithmetic is "
      "correct; the phrasing points at the wrong subset. It does not affect "
      "the conclusion.\n")

    A("## The conclusion\n")
    A(f"**`{W4}`'s directional signal is real, but the evidence base is now "
      f"held to a stricter standard than 'refused' implies.** "
      f"{n('os_below_lo_pct::'+W4,'{:.1f}')}% of its rows fall below the lower "
      f"bound and only {n('os_above_hi_pct::'+W4,'{:.1f}')}% above the upper "
      f"one, so scoring it one-sided barely moves it: "
      f"{n('os_two_sided_pct::'+W4,'{:.1f}')}% to "
      f"{n('os_one_sided_pct::'+W4,'{:.1f}')}%. The damage is real and on the "
      f"side that matters -- but see 'What changed' below: this cell is now "
      f"classified `insufficient_evidence`, not `refused`, because it rests "
      f"on only {n('os_distinct_checkpoints::'+W4)} checkpoints.\n")
    A(f"But the evidence is narrower than the label. Those "
      f"{n('os_scored_rows::'+W4)} rows are "
      f"{n('os_distinct_model_benchmark::'+W4)} distinct (model, benchmark) "
      f"results from {n('os_distinct_checkpoints::'+W4)} checkpoints in "
      f"{n('os_distinct_families::'+W4)} family. **The claim the data supports "
      f"is about small Qwen, not about every model under 2B.**\n")
    A(f"**`{W8}` is substantially a scoring artefact.** "
      f"{n('os_above_hi_pct::'+W8,'{:.1f}')}% of its rows sit *above* the upper "
      f"bound -- the model beat the envelope, which is not a risk anyone needs "
      f"protecting from. Counting only losses below the lower bound moves it "
      f"from {n('os_two_sided_pct::'+W8,'{:.1f}')}% to "
      f"{n('os_one_sided_pct::'+W8,'{:.1f}')}%, close to the 90% it claims.\n")
    A("What remains after that is one checkpoint. Resampling whole checkpoints "
      f"puts a 90% interval of [{n('os_boot90_lo::'+W8,'{:.0f}')}%, "
      f"{n('os_boot90_hi::'+W8,'{:.0f}')}%] around the headline figure. That "
      f"span cannot distinguish *this cell is uncalibrated* from *one Llama "
      f"checkpoint is an outlier*, and it straddles the "
      f"{n('refuse_below_pct','{:.0f}')}% refusal line -- neither of which a "
      f"point estimate alone would reveal. By contrast `{W4}` resamples to "
      f"[{n('os_boot90_lo::'+W4,'{:.0f}')}%, {n('os_boot90_hi::'+W4,'{:.0f}')}%], "
      f"a narrower interval sitting entirely below the line -- better "
      f"evidenced, but still only 2 checkpoints, which is what now holds it "
      f"back from being called a confident refusal.\n")

    A("## What the one-sided figure should be compared against\n")
    A(f"A fair objection: the tool prints a two-sided 90% interval, so "
      f"measuring a one-sided property and comparing it to 90% could look "
      f"like choosing the flattering number. It is the opposite.\n")
    A(f"The interval is symmetric -- a mean plus or minus one conformal "
      f"half-width on the absolute residual -- so the 10% permitted to miss is "
      f"split across two tails. Pooled across all "
      f"{n('pooled_scored_rows')} scored rows that split is "
      f"{n('pooled_below_lo_pct','{:.1f}')}% below the lower bound and "
      f"{n('pooled_above_hi_pct','{:.1f}')}% above it, giving a pooled "
      f"one-sided coverage of {n('pooled_one_sided_pct','{:.1f}')}%. **The "
      f"nominal one-sided level for this construction is therefore about 95%, "
      f"not 90%.**\n")
    A(f"Judging a one-sided measurement against 90% is the lenient comparison. "
      f"Both refused cells fail it anyway: "
      f"{n('os_one_sided_pct::'+W4,'{:.1f}')}% and "
      f"{n('os_one_sided_pct::'+W8,'{:.1f}')}%. Against the ~95% that the "
      f"construction actually implies they fail by a wider margin. The "
      f"refusals are not a product of the scoring choice.\n")
    A("## What has changed, and what has not\n")
    A("**Done.** Every coverage figure now reports the number of distinct "
      "checkpoints and families beside it, in the JSON artifact and in the "
      "tool's own output. The same standard already applied to training "
      "support now applies to coverage.\n")
    A(f"**Also done.** The refusal threshold now scores one-sided coverage. "
      f"The tool's behaviour matches what this document argues is correct.\n")
    A(f"**The outcome was not what was expected, and that is worth recording.** "
      f"The change was made in the expectation that `{W8}` would stop being "
      f"refused. It did not stop being flagged -- its refusal threshold is "
      f"{n('refuse_below_pct','{:.0f}')}%, not the 90% the interval "
      f"advertises, and {n('os_one_sided_pct::'+W8,'{:.1f}')}% is still below "
      f"it. What changed is the criterion and the number reported: `{W8}` is "
      f"now shown as {n('os_one_sided_pct::'+W8,'{:.1f}')}% rather than "
      f"{n('os_two_sided_pct::'+W8,'{:.1f}')}%, a fairer description of the "
      f"same evidence.\n")
    A("The finding stands regardless: the two cells fail for different "
      "reasons, and the tool now measures the one that matters. But it would "
      "have been easy to report this change as having flipped a refusal, and "
      "it did not.\n")
    A("## The third state: insufficient evidence\n")
    A(f"A cell resting on {n('os_distinct_checkpoints::'+W4)} checkpoints and "
      f"one resting on {n('os_distinct_checkpoints::'+W8)} were being treated "
      "as the same kind of evidence, and the tool had only two states: "
      "answer, or refuse. Neither fit a cell where the honest position is "
      "*there is not enough evidence to judge*. A second proposal from the "
      "same commenter resolved this: apply the three-checkpoint floor to the "
      "coverage judgment itself (not just training support), and add a "
      "checkpoint-cluster bootstrap interval on the one-sided statistic; a "
      "cell fails into `insufficient_evidence` -- not `refused` -- if it has "
      f"fewer than {n('min_cell_checkpoints')} checkpoints or its bootstrap "
      "interval straddles the refusal line.\n")
    A("Both parts of the proposal were verified independently before "
      "implementation. The checkpoint-count asymmetry was confirmed by "
      "reading `rank.py` directly: the three-checkpoint floor "
      "(`MIN_CELL_CHECKPOINTS`) gated Tier A training support but was never "
      "consulted by the refusal check. The bootstrap-statistic mismatch was "
      "confirmed by reading `one_sided_audit.py` directly: its cluster "
      "bootstrap resampled the two-sided `ok` column even though the "
      "refusal decision judges the one-sided statistic -- now fixed to "
      "bootstrap the one-sided indicator instead. The claim that a 2-cluster "
      "bootstrap 'degenerates trivially' was confirmed combinatorially: "
      "drawing 2 checkpoints with replacement from a pool of 2 has exactly "
      "4 equally likely outcomes, collapsing to only 3 distinct resample "
      "compositions -- not enough to produce a meaningful percentile "
      "interval.\n")
    A(f"**The result reclassifies both previously-refused cells.** Neither "
      f"`{W4}` (2 checkpoints, below the floor) nor `{W8}` (5 checkpoints, "
      "but its corrected bootstrap interval "
      f"[{n('os_boot90_lo::'+W8,'{:.0f}')}%, {n('os_boot90_hi::'+W8,'{:.0f}')}%] "
      f"straddles the {n('refuse_below_pct','{:.0f}')}% line) is a confident "
      "refusal any more -- both are `insufficient_evidence`. Applying the "
      "floor to every scheme/size cell, not only these two, moved "
      f"{n('n_cells_insufficient_evidence')} of "
      f"{n('n_cells_total')} scheme/size cells into "
      "`insufficient_evidence` in total, including several with "
      "comfortably high point-estimate coverage (94-100%) whose bootstrap "
      "intervals also straddle the line. This is a materially larger "
      "effect than the two-cell scope this document originally covered, "
      "and it is reported in full in `rank.py`'s own output rather than "
      "summarized away here.\n")
    A("## Credit\n")
    A("This finding came from outside the project, from an AI collaborator "
      "working with the OpenLanguageModel maintainers (disclosed as such in "
      "their Reddit bio): re-ran the code, reproduced the artifact, went to "
      "the raw rows, and identified a real inconsistency between what our "
      "own comment said and what the refusal logic did, then proposed and "
      "helped scope the fix that resolved it. It is the first external "
      "technical contribution the project has received, and it improved it. "
      "The technical work is credited on its merits; it is not represented "
      "here as a human reviewer's.\n")
    open(os.path.join(ROOT, "ONE_SIDED_COVERAGE.md"), "w").write("\n".join(L) + "\n")
    print("wrote ONE_SIDED_COVERAGE.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
