"""Generate BIAS_CORRECTION.md and TOOL_SUMMARY.md from computed values."""
from __future__ import annotations
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from verify_claims import registry  # noqa: E402
import rank as R  # noqa: E402
import feedback  # noqa: E402

HERE=os.path.dirname(__file__); ROOT=os.path.join(HERE,"..")
REG=registry()
def v(k): return REG[k][0]
def n(k,f="{:.0f}"):
    x=v(k); return f"{f.format(x)}<!-- claim: {k} = {x:.4f} -->"

def bias_doc():
    L=[];A=L.append
    A("# Correcting a conformal interval for survivorship bias\n")
    A("*Status: the identification result and the exact coverage-degradation "
      "formula hold and are validated. The tail-extrapolation correction was "
      "built, tested, and **does not work well enough to ship**. Reported "
      "here rather than quietly dropped.*\n")
    A("> **Generated by `src/gen_bias_doc.py` from computed values and "
      "re-checked by\n> `src/verify_claims.py`. Do not hand-edit figures; "
      "regenerate instead.**\n")
    A("---\n")
    A("## The problem\n")
    A("RedHatAI publishes quantization recipes that worked. Configs that "
      "damaged a model were never released, so every interval computed from "
      "that corpus is an interval over survivors. BenchPress "
      "(arXiv:2606.24020) has the same exposure and does not address it: its "
      "score matrix is built from published model cards too.\n")
    A("## 1. Identification (holds)\n")
    A("If a fraction `pi` of attempted configs went unpublished and censoring "
      "is on the outcome, the observed `G` and true `F` satisfy "
      "`F(x) = pi + (1-pi) G(x)`, so `F^-1(q) = G^-1((q-pi)/(1-pi))` for "
      "`q > pi`. When `q <= pi` the true quantile lies below everything ever "
      "observed and is **not identified**.\n")
    A("A 90% interval needs `q = 0.05`. So **any censoring rate above 5% puts "
      "the lower bound outside what published data can determine**, for us "
      "and for anyone else using published cards.\n")
    A("## 2. Exact coverage degradation (holds, validated)\n")
    A("The naive lower bound leaves exactly `pi + (1-pi)*alpha/2` of the true "
      "population below it. No distributional assumption is needed.\n")
    A("| assumed censoring | true lower-miss rate | what your '90%' interval really is |")
    A("|---|---|---|")
    for pi in ("0.0","0.05","0.1","0.15","0.2","0.3"):
        k1,k2=f"bias_miss_rate::{pi}",f"bias_effective::{pi}"
        if k1 not in REG: continue
        A(f"| {float(pi)*100:.0f}% | {n(k1,'{:.4f}')} | "
          f"{n(k2,'{:.1f}')}% |")
    A("")
    A(f"Validated against simulation: at a true censoring rate of 15% the "
      f"formula predicts {n('bias_naive_mass::mixture','{:.4f}')} and "
      f"simulation measures the same value.\n")
    A("**This is the usable output.** It does not tell you where the bound "
      "should be, but it tells you what the bound you have is actually "
      "worth, which is enough to stop someone treating a 90% label as 90%.\n")
    A("## 3. The tail-extrapolation correction (built, tested, failed)\n")
    A("We fitted a generalised Pareto distribution to the observed left tail "
      "(peaks-over-threshold, method of moments) and extrapolated below the "
      "observed minimum to place a corrected lower bound.\n")
    A("Tested against simulation with known truth and known censoring, in two "
      "worlds:\n")
    A("| censored configs are... | naive mass below bound | after correction | share of bias removed |")
    A("|---|---|---|---|")
    for sc,lab in (("smooth","a continuation of the same tail (assumption HOLDS)"),
                   ("mixture","a distinct failure mode (assumption FAILS)")):
        k=f"bias_gap_closed_pct::{sc}"
        if k not in REG: continue
        A(f"| {lab} | {n('bias_naive_mass::'+sc,'{:.4f}')} | "
          f"{v('bias_naive_mass::'+sc) - (v(k)/100)*(v('bias_naive_mass::'+sc)-0.05):.4f}"
          f"<!-- claim: bias_after_correction::{sc} = "
          f"{v('bias_naive_mass::'+sc) - (v(k)/100)*(v('bias_naive_mass::'+sc)-0.05):.4f} --> | "
          f"{n(k,'{:.0f}')}% |")
    A("")
    A(f"Even in the world where its own assumption holds, the correction "
      f"removes only {n('bias_gap_closed_pct::smooth','{:.0f}')}% of the "
      f"bias. **That is not good enough to ship.** An earlier version was "
      f"worse than useless: it moved the bound the wrong way, because the "
      f"tail probability was normalised by the observed exceedance fraction "
      f"instead of the true mass below the threshold. The synthetic check "
      f"caught that; the audit gate is what made the check exist.\n")
    A("## 4. The fix: real adversarial anchors (DONE)\n")
    A(f"We rented an A100 and measured {n('adv_rows')} rows across "
      f"{n('adv_models')} models and {n('adv_recipes')} recipes, including a "
      f"correctly-configured control arm on the same items.\n")
    A(f"The control arm matters: our correct-w4a16 control measured "
      f"{n('adv_control_mean','{:+.2f}')}pp where the published w4a16 mean is "
      f"{n('lo::w4a16','{:+.2f}')}..{n('hi::w4a16','{:+.2f}')}. Our simplified "
      f"GPTQ is worse than production llm-compressor, and the harness differs "
      f"(0-shot vs 5-shot MMLU). So the usable quantity is **excess over "
      f"control**, which cancels both.\n")
    A("| recipe | rows | mean excess | worst excess |")
    A("|---|---|---|---|")
    A(f"| pooled w4a16 bad recipes | {n('adv_excess_n')} | "
      f"{n('adv_excess_mean','{:+.2f}')}pp | "
      f"{n('adv_excess_worst','{:+.2f}')}pp |")
    A("")
    A("Modelling a user's recipe as competent with probability 1-pi and "
      "botched with probability pi, the corrected lower bound becomes:\n")
    A("| assumed botch rate | corrected w4a16 lower bound |")
    A("|---|---|")
    for pi in ("0.0","0.05","0.1","0.15","0.2","0.3"):
        k=f"corrected_lower::{pi}"
        if k in REG:
            A(f"| {float(pi)*100:.0f}% | {n(k,'{:+.2f}')}pp |")
    A("")
    A("**Honest note on the gemma-3-1b case, twice corrected.** The shipped "
      "symmetric conformal bound is -2.87pp and catches 2 of its 6 "
      "benchmarks. A wider asymmetric empirical band catches 5 of 6. We "
      "briefly concluded the tool should therefore switch to the empirical "
      "band -- that was wrong. Measured under the strict held-out protocol "
      f"(`src/interval_shape.py`), conformal covers "
      f"{n('finite_conf_cov_pct','{:.1f}')}% at "
      f"{n('finite_conf_width','{:.2f}')}pp width against empirical "
      f"{n('finite_emp_cov_pct','{:.1f}')}% at "
      f"{n('finite_emp_width','{:.2f}')}pp, on the rows where the empirical "
      f"band is defined at all; its apparent advantage came from returning "
      f"+/-infinity on {n('inf_share_pct','{:.0f}')}% of rows. **Conformal stays, and gemma stays a "
      "miss.** The correct reading is that gemma is an example of the tail "
      "this tool does not describe, which is what the bias correction is "
      "for -- not evidence that the interval shape is wrong.\n")
    A("### Session 2: matching the published harness, and what it exposed\n")
    A(f"Our first run scored MMLU 0-shot and got "
      f"{n('s2_pub_qwen05','{:.2f}')} published versus a much lower measured "
      f"value. Rerunning at 5-shot with letter scoring reproduces published "
      f"base accuracy closely: {n('s2_base_qwen05','{:.2f}')} against "
      f"{n('s2_pub_qwen05','{:.2f}')} for Qwen2.5-0.5B, and "
      f"{n('s2_base_qwen15','{:.2f}')} against {n('s2_pub_qwen15','{:.2f}')} "
      f"for Qwen2.5-1.5B. The harness confound is closed.\n")
    A("Closing it exposed a second, larger one:\n")
    A("- Our **correctly-configured** w4a16 control is materially worse than "
      "production. Red Hat published w4a16 for the same two checkpoint "
      "families, so this is a matched head-to-head rather than a comparison "
      "against a pooled average:\n")
    A("")
    A("| model | published delta | our control delta | gap |")
    A("|---|---|---|---|")
    A(f"| Qwen2.5-0.5B | {n('ctrl_pub_delta::Qwen2_5-0_5B','{:+.2f}')}pp | "
      f"{n('ctrl_our_delta::Qwen2_5-0_5B','{:+.2f}')}pp | "
      f"{n('ctrl_gap::Qwen2_5-0_5B','{:+.2f}')}pp |")
    A(f"| Qwen2.5-1.5B | {n('ctrl_pub_delta::Qwen2_5-1_5B','{:+.2f}')}pp | "
      f"{n('ctrl_our_delta::Qwen2_5-1_5B','{:+.2f}')}pp | "
      f"{n('ctrl_gap::Qwen2_5-1_5B','{:+.2f}')}pp |")
    A("")
    A(f"Mean gap {n('ctrl_mean_gap','{:+.2f}')}pp, "
      f"**{n('ctrl_ratio_x','{:.1f}')}x more damaging**, significant at "
      f"z = {n('ctrl_min_z','{:.1f}')} and {n('ctrl_max_z','{:.1f}')}. An "
      f"earlier draft of this section said 5.1x; that compared our two small "
      f"models against a published mean pooled over all sizes, and published "
      f"w4a16 damage is size-dependent. The matched figure is "
      f"{n('ctrl_ratio_x','{:.1f}')}x.\n")
    A(f"The cause is explained rather than mysterious: we calibrate on 24 "
      f"texts of 256 tokens where production llm-compressor defaults to 512 "
      f"samples of 2048, about **{n('calib_ratio_x','{:.0f}')}x less "
      f"calibration data**, and we omit activation reordering (documented as "
      f"worth up to ~2pp), zero points, and sequential requantization. Our "
      f"control is a legitimately under-calibrated recipe, not a broken "
      f"one.\n")
    A("*Caveat on the match:* the published rows are the base checkpoints "
      "and ours are the -Instruct variants. Base MMLU accuracies agree to "
      f"{n('ctrl_baseagree::Qwen2_5-0_5B','{:.2f}')}pp and "
      f"{n('ctrl_baseagree::Qwen2_5-1_5B','{:.2f}')}pp, so they are "
      f"comparable, but not the identical artifact.\n"
      f"- SmolLM-135M had to be dropped from this analysis: at "
      f"{n('s2_smollm_base','{:.2f}')} on MMLU it is statistically at chance "
      f"(4-way, so 25.0), so its "
      f"deltas are noise. Including it diluted the control estimate and made "
      f"the gap look half as large as it is.\n")
    A(f"So the anchors measure **excess damage of a bad recipe relative to a "
      f"mediocre one**, not relative to a production one. The remaining "
      f"anchor set is {n('s2_excess_n')} rows from 2 models "
      f"(mean {n('s2_excess_mean','{:+.2f}')}pp, worst "
      f"{n('s2_excess_worst','{:+.2f}')}pp) - thin, and stated as thin.\n")
    A(f"**The correction is anchor-dependent.** Using the 0-shot anchors "
      f"versus the 5-shot ones moves the corrected bound by "
      f"{n('s2_protocol_sensitivity','{:.2f}')}pp at a 20% botch rate. "
      f"Neither set is authoritative: the 0-shot set is larger but its "
      f"harness did not match published, the 5-shot set matches but is tiny "
      f"and rests on a weak control. We therefore do not publish a single "
      f"corrected number.\n")
    A("**What is still not identified:** pi. We now measure the tail shape "
      "instead of assuming it, but how often a real user botches a recipe is "
      "not something our data can tell us.\n")
    A("### Can pi be bounded from public evidence?\n")
    A("We searched for a credible failure-rate figure and **did not find "
      "one**. No survey, dataset or paper reports how often practitioners "
      "botch a quantization run, and the natural proxy -- counting bug "
      "reports -- has no usable denominator, because nobody opens an issue "
      "when quantization works. We are not going to manufacture a number "
      "from that.\n")
    A("What the public record *does* corroborate is the **magnitude** of our "
      "adversarial measurements, which matters for the tail shape even "
      "though it says nothing about frequency:\n")
    A("| reported failure | measured loss |")
    A("|---|---|")
    A("| AWQ W4A16 on Gemma-3, CareQA (llm-compressor issue #2522) | "
      "85.6% -> 69.2%, about -16pp, while GPTQ on the same model held 83.6% |")
    A("| `quantization_2of4_sparse_w4a16` (issue #1638) | MMLU-Pro collapsed "
      "to 0.08 |")
    A("| llm-compressor vs auto_gptq GPTQ (issue #1123) | ARC-C 0.35 vs 0.49, "
      "about -14pp from implementation choice alone |")
    A("")
    A(f"Our pooled w4a16 excess-over-control is "
      f"{n('adv_excess_mean','{:+.2f}')}pp with a worst of "
      f"{n('adv_excess_worst','{:+.2f}')}pp. Independently reported "
      f"real-world failures land in the same -14 to -16pp region, which is "
      f"external corroboration that our deliberately-bad configs produce "
      f"realistic damage rather than artificial worst cases.\n")
    A("**Decision: pi stays a user-supplied sensitivity parameter.** The tool "
      "reports the corrected bound across a range of pi rather than picking "
      "one, because picking one would be the least defensible number in the "
      "product.\n")
    A("## 5. Relationship to BenchPress\n")
    A("BenchPress does not address selection bias at all. Its reliability "
      "layer estimates how wrong a prediction is likely to be *within* the "
      "published distribution, which is a different axis from whether the "
      "published distribution represents reality. That gap is real and "
      "unclaimed. We have not closed it either - we have characterised it "
      "exactly and shown that one plausible fix does not work.\n")
    open(os.path.join(ROOT,"BIAS_CORRECTION.md"),"w").write("\n".join(L)+"\n")

def tool_doc():
    t=R.build_table(); meta=t["_meta"]; cc=R.load_cell_coverage()
    ranked,_=R.rank([k for k in t if k!="_meta"],t)
    L=[];A=L.append
    A("# Quantization scheme risk tool - what it is, honestly\n")
    A("> ## ⚠ Read this first\n"
      f"> We quantized real models on an A100 with deliberately-bad configs and "
      f"measured losses to **{n('adv_worst_delta','{:.1f}')}pp**. The largest "
      f"single effect was wrong scale granularity: per-tensor instead of "
      f"per-group.\n"
      f"> {n('adv_bad_over_3pp')} of {n('adv_bad_rows')} faulted rows lost 3pp "
      f"or more. Separately, {n('adv_control_over_3pp')} of "
      f"{n('adv_control_rows')} rows from our *correct* control arm did too. "
      f"The worst loss anywhere in the published corpus this tool is "
      f"calibrated on is {n('worst::w4a16','{:.2f}')}pp.\n"
      f"> **Scope:** that left tail was measured only at "
      f"{n('adv_max_params_b','{:.1f}')}B and below, a band this tool refuses "
      f"to answer for at w4a16. It shows catastrophic damage is reachable. It "
      f"is not a measured bound for larger models.\n"
      "> **Treat every interval below as a floor on risk, not a ceiling.** "
      "Published recipes are the ones that worked; yours may not be one of "
      "them.\n")
    A("> *What we can and cannot back up:* the losses above are measured and "
      "reproducible. How much worse a botched recipe is **than a "
      "professionally-tuned one** is not something we can yet put a number "
      "on - see \"Evidence quality\" below.\n")
    A("A calibrated, audited, deliberately conservative decision aid for "
      f"{n('n_schemes')} "
      "specific quantization schemes. Not a predictor. Not novel relative to "
      "BenchPress on the core mechanism.\n")
    A(f"Built on {n('n_rows')} published evaluations from "
      f"{n('n_checkpoints')} checkpoints across {n('n_families')} model "
      f"families (RedHatAI model cards).\n")
    A("> **Generated by `src/gen_bias_doc.py` from computed values and "
      "re-checked by\n> `src/verify_claims.py`. Do not hand-edit figures; "
      "regenerate instead.**\n")
    A("## The part that matters: it refuses\n")
    A("Most of what this tool does is give you a calibrated interval. The part "
      "worth your attention is what it does when it should not give you one.\n")
    A(f"Two (scheme, size) cells have measured coverage so far below the 90% "
      f"they advertise that the tool declines to answer for them at all: "
      f"`w4a16|<2B` at "
      f"{n('cell_coverage_pct::w4a16|<2B','{:.1f}')}% over "
      f"{n('cell_rows::w4a16|<2B')} scored rows, and `w8a16|>10B` at "
      f"{n('cell_coverage_pct::w8a16|>10B','{:.1f}')}% over "
      f"{n('cell_rows::w8a16|>10B')}. It prints `INSUFFICIENT CALIBRATION`, "
      f"shows the coverage it actually measured, and stops. A further "
      f"{n('n_cells_blocked_from_tier_a')} cells are barred from the top tier "
      f"for resting on fewer than {n('min_cell_checkpoints')} distinct "
      f"checkpoints.\n")
    A("A risk estimate is only worth having if it tells you when not to trust "
      "it. The refused cells are exactly where a confident-sounding number "
      "would do the most damage.\n")
    A("## Try it\n")
    A("No network, no API key, no GPU; three common packages. The "
      "`w4a16 --size 1.5B` line is the one to run first -- it is the one that "
      "declines:\n")
    A("```bash\n"
      "cd quant-delta-predictor\n"
      "python3 -m venv .venv && ./.venv/bin/pip install numpy pandas scipy\n"
      "./.venv/bin/python src/rank.py w4a16 --size 1.5B   # refuses, and says why\n"
      "./.venv/bin/python src/rank.py                     # ranks every scheme\n"
      "```\n")
    A("## What it does\n")
    A("Input a quantization scheme, optionally a model size band. Output a "
      "90% interval on the accuracy delta, the worst loss ever observed, the "
      "measured coverage for that cell, and the flags that apply.\n")
    A("| scheme | 90% interval (pp) | worst observed | % losing >3pp | evals | tier |")
    A("|---|---|---|---|---|---|")
    for e in ranked:
        s=e["scheme"]
        A(f"| {s} | [{n('lo::'+s,'{:+.2f}')}, {n('hi::'+s,'{:+.2f}')}] | "
          f"{n('worst::'+s,'{:+.2f}')}pp | {n('severe_pct::'+s,'{:.1f}')}% | "
          f"{n('n::'+s)} | **{e['tier']}** |")
    A("")
    A("## The refused cells, in full\n")
    A(f"The two cells named above, with the measured coverage behind each "
      f"refusal:\n")
    for key in sorted(k for k,vv in cc["cells"].items()
                      if vv["coverage"]<R.REFUSE_BELOW
                      and vv["scored_rows"]>=R.REFUSE_MIN_ROWS):
        A(f"- `{key}` - measured {n('cell_coverage_pct::'+key,'{:.1f}')}% over "
          f"{n('cell_rows::'+key)} scored rows")
    A("")
    A(f"`fp8|<2B` is the clearest case of the support rule doing work: "
      f"{n('cell_coverage_pct::fp8|<2B','{:.1f}')}% measured coverage, which "
      f"looks perfect, from a single checkpoint "
      f"({n('cell_train_ckpt2::fp8|<2B')}) measured many ways. Rows from one "
      f"quantization run are correlated views of that run, not independent "
      f"evidence, so the cell is capped below Tier A.\n")
    A("## What it cannot do\n")
    A(f"- {n('intervals_excluding_zero')} of 6 intervals exclude zero: it can "
      f"never say a scheme *will* cost accuracy.")
    A(f"- {n('n_big_losses_below_floor')} of {n('n_big_losses')} observed "
      f"losses worse than 3pp fell below their interval floor.")
    A("- It is built on configs that were published, i.e. that worked. See "
      "`BIAS_CORRECTION.md` for exactly how much that inflates the apparent "
      "coverage.")
    A("- It reads 2 inputs and nothing else about your model.")
    A("- It predicts an **accuracy** delta and nothing else. Whether a "
      "compressed model stays well calibrated -- whether it still knows what "
      "it does not know -- is a separate question this tool does not touch. "
      "See *What's next* below.")
    A(f"- **Every one of the {n('n_rows')} calibration rows comes from a "
      f"single publisher (RedHatAI) using a single toolchain "
      f"(llm-compressor).** Holding out a model family tests transfer across "
      f"*models*; nothing here tests transfer across *quantization "
      f"practitioners*. Our own control arm is direct evidence that this "
      f"matters: run by us rather than by Red Hat, the same scheme on "
      f"comparable checkpoints came out {n('ctrl_ratio_x','{:.1f}')}x more "
      f"damaging. Read these intervals as what a competent, well-tuned "
      f"pipeline achieves -- not as what an arbitrary pipeline will.\n")
    A("## What's next\n")
    A("The clearest gap is that accuracy is not the whole of deployment risk. "
      "Tong et al. ([arXiv:2606.01850](https://arxiv.org/abs/2606.01850)) "
      "benchmark 12 compressed LLMs with conformal prediction and find that "
      "compression frequently *decouples* the two: a model can hold its "
      "accuracy while its prediction sets inflate, meaning its confidence has "
      "degraded even though its answers have not. A natural extension would be "
      "to predict prediction-set inflation alongside the accuracy delta. That "
      "requires running the compressed model, which is a different pipeline "
      "from this tool's forecast-before-running approach, so it is a genuine "
      "piece of work rather than an addition. It is not built and not in "
      "progress.\n")
    A("## Evidence quality: what is clean and what is not\n")
    A("**Clean, and safe to rely on:**\n")
    A(f"- *Existence proof.* Deliberately-bad configs produce catastrophic "
      f"damage: worst measured {n('adv_worst_delta','{:.1f}')}pp raw, "
      f"{n('adv_bad_over_3pp')} of {n('adv_bad_rows')} faulted rows losing "
      f"3pp. This does not depend on any baseline.\n"
      f"- *Harness alignment.* Re-running MMLU at 5-shot with letter scoring "
      f"reproduces published base accuracy to "
      f"{n('s2_base_qwen05','{:.2f}')} against "
      f"{n('s2_pub_qwen05','{:.2f}')}, and {n('s2_base_qwen15','{:.2f}')} "
      f"against {n('s2_pub_qwen15','{:.2f}')}. Our measurements are on the "
      f"same footing as the published corpus.\n")
    A("**Caveated, and not to be quoted as a bound:**\n")
    A(f"- *Excess over control.* Our own correctly-configured control is "
      f"{n('ctrl_ratio_x','{:.1f}')}x more damaging than published w4a16 on "
      f"closely comparable checkpoints (mean gap "
      f"{n('ctrl_mean_gap','{:+.2f}')}pp), "
      f"because we calibrate on about {n('calib_ratio_x','{:.0f}')}x less "
      f"data than production. So excess-over-control measures **bad recipe "
      f"versus mediocre recipe**, not versus production. It is a "
      f"*conservative anchor*, not a bound: we cannot demonstrate "
      f"monotonicity on {n('s2_excess_n')} rows from 2 models. "
      f"*Not identical artifacts:* the published rows are the base "
      f"checkpoints and ours the -Instruct variants; their base MMLU agrees "
      f"to {n('ctrl_baseagree::Qwen2_5-0_5B','{:.2f}')}pp and "
      f"{n('ctrl_baseagree::Qwen2_5-1_5B','{:.2f}')}pp, so they are "
      f"comparable but not the same checkpoint.\n"
      f"- *No corrected point estimate.* The selection-bias correction moves "
      f"by {n('s2_protocol_sensitivity','{:.2f}')}pp depending on which "
      f"anchor set is used. We publish a range and refuse a single "
      f"number.\n")
    A("## Helping close the gap\n")
    A("This tool's calibration is **static and drawn only from published "
      "model cards**. That has a known, measured limitation: published "
      "recipes are the ones that worked, and two (scheme, size) cells have "
      "too little data for the tool to answer at all. Real results from real "
      "runs are the fastest way to fix that.\n")
    A("If you evaluate a quantized model yourself, the numbers are worth "
      "sending back - especially for a combination the tool refused to "
      "answer, since those are the gaps.\n")
    _form = (feedback.config().get("form_url") or "").strip()
    if _form:
        A(f"**Report a result or just give feedback:** <{_form}>\n")
        A("The page has two sections. The first takes a measured result; the "
          "second is a free-text box you can send on its own, with nothing "
          "else filled in.\n")
    A("**What this currently is, precisely:** a hosted collection form and a local "
      "log of which combinations people ask about. Submitted results do "
      "*not* flow into the envelope automatically. A human validates them "
      "with `src/adversarial_schema.py` and re-runs the build. There is no "
      "backend, no ingestion pipeline and no telemetry; the request log "
      "stays on your own machine. Run `./.venv/bin/python src/rank.py "
      "--form-fields` to "
      "see exactly what is collected.\n")
    A("## Relation to prior work\n")
    A("[BenchPress](https://arxiv.org/abs/2606.24020) (Zeng & "
      "Papailiopoulos, Microsoft Research, 2026) already published the core "
      "mechanism: predict an eval result, estimate whether to trust it, wrap "
      "it in a conformal interval, decide whether to skip the real run. "
      "Their method is more sophisticated than ours - a learned reliability "
      "estimator and a risk-normalised conformal wrapper, with public code "
      "and data.\n")
    A("This tool differs in three ways, none of which is a better mechanism:\n")
    A("1. **Domain and estimand.** Paired quantization deltas, not absolute "
      "benchmark scores. BenchPress contains no quantized checkpoints.\n"
      "2. **It refuses.** Where measured per-cell coverage is poor or "
      "support is thin, it declines to emit a number. BenchPress flags risk "
      "but still returns an interval.\n"
      "3. **It characterises its own selection bias** exactly, which "
      "BenchPress does not attempt. We have not *corrected* that bias - see "
      "`BIAS_CORRECTION.md` for the attempt that failed.\n")
    A("If you want per-model eval prediction, use BenchPress. This is for the "
      "narrower question of whether a given quantization scheme is safe "
      "enough to adopt without re-running your benchmarks.\n")
    A("**Closer in domain, different in purpose.** Tong et al., *Does "
      "Compression Preserve Uncertainty?* "
      "([arXiv:2606.01850](https://arxiv.org/abs/2606.01850), Wuhan "
      "University of Technology and NTU, 2026) apply conformal prediction "
      "directly to quantized and sparse LLMs -- 12 models from 1B to 70B, "
      "W4A16 among the configurations, five tasks. That is a much closer "
      "domain than BenchPress. The purpose is different: their conformal "
      "sets are built over *label space* from a compressed model's own output "
      "probabilities, so the method measures how good a model's uncertainty "
      "is **after you have run it**. Ours is built over *historical accuracy "
      "deltas across checkpoints*, to give you an interval **before you run "
      "anything**. They measure; this forecasts. Their paper is the better "
      "reference for whether a compressed model still knows what it does not "
      "know; it does not answer how much accuracy a scheme will cost you.\n")
    open(os.path.join(ROOT,"TOOL_SUMMARY.md"),"w").write("\n".join(L)+"\n")

if __name__=="__main__":
    bias_doc(); tool_doc(); print("wrote BIAS_CORRECTION.md and TOOL_SUMMARY.md")
