"""Emit paper/numbers.tex from the claims registry.

Every figure in the paper is a macro defined here, so no number in main.tex is
hand-typed. Changing the data and re-running the pipeline updates the paper.
"""
from __future__ import annotations
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "src"))
from verify_claims import registry  # noqa: E402

R = {k: v[0] for k, v in registry().items()}

# macro name -> (registry key, format)
M = {
    "Nrows": ("n_rows", "{:.0f}"), "Nckpt": ("n_checkpoints", "{:.0f}"),
    "Nfam": ("n_families", "{:.0f}"), "Nsch": ("n_schemes", "{:.0f}"),
    "MinCkpt": ("min_cell_checkpoints", "{:.0f}"),
    "NpredNums": ("n_numbers_in_predictor", "{:.0f}"),
    "AdvWorst": ("adv_worst_delta", "{:.1f}"),
    "AdvBadRows": ("adv_bad_rows", "{:.0f}"),
    "AdvBadOver": ("adv_bad_over_3pp", "{:.0f}"),
    "AdvCtrlRows": ("adv_control_rows", "{:.0f}"),
    "AdvCtrlOver": ("adv_control_over_3pp", "{:.0f}"),
    "AdvMaxB": ("adv_max_params_b", "{:.1f}"),
    "CtrlRatio": ("ctrl_ratio_x", "{:.1f}"),
    "CtrlGap": ("ctrl_mean_gap", "{:+.2f}"),
    "CalibRatio": ("calib_ratio_x", "{:.0f}"),
    "CtrlZmin": ("ctrl_min_z", "{:.1f}"), "CtrlZmax": ("ctrl_max_z", "{:.1f}"),
    "BaseQwenSmall": ("s2_base_qwen05", "{:.2f}"),
    "PubQwenSmall": ("s2_pub_qwen05", "{:.2f}"),
    "BaseQwenMid": ("s2_base_qwen15", "{:.2f}"),
    "PubQwenMid": ("s2_pub_qwen15", "{:.2f}"),
    "ProtoSens": ("s2_protocol_sensitivity", "{:.2f}"),
    "ExcessN": ("s2_excess_n", "{:.0f}"),
    "IntervalsExclZero": ("intervals_excluding_zero", "{:.0f}"),
    "BigLossBelow": ("n_big_losses_below_floor", "{:.0f}"),
    "BigLoss": ("n_big_losses", "{:.0f}"),
    "CellsBlocked": ("n_cells_blocked_from_tier_a", "{:.0f}"),
    "PubChecked": ("pub_publishers_checked", "{:.0f}"),
    "PubCards": ("pub_cards_inspected", "{:.0f}"),
    "PubOthersCards": ("pub_others_cards", "{:.0f}"),
    "PubOthersCount": ("pub_others_count", "{:.0f}"),
    "PubOthersPaired": ("pub_others_paired_cards", "{:.0f}"),
    "PubOthersVerified": ("pub_others_verified_rows", "{:.0f}"),
    "PubCtrlVerified": ("pub_control_verified_rows", "{:.0f}"),
}
SCHEMES = ["fp8", "w8a8_int", "fp8_dynamic", "w8a16", "w4a16", "nvfp4"]
CAMEL = {"fp8": "Fpeight", "w8a8_int": "Weightint", "fp8_dynamic": "Fpdyn",
         "w8a16": "Weightsixteen", "w4a16": "Wfour", "nvfp4": "Nvfp"}
PRED = ["scheme_mean", "global_mean", "scheme_x_bench", "ridge", "bench_mean",
        "grad_boost"]
PCAMEL = {"scheme_mean": "Schememean", "global_mean": "Globalmean",
          "scheme_x_bench": "Schemebench", "ridge": "Ridge",
          "bench_mean": "Benchmean", "grad_boost": "Gradboost"}


def main():
    out = ["% GENERATED by paper/gen_numbers.py from the claims registry.",
           "% Do not hand-edit. Re-run the generator instead.", ""]
    miss = []
    for macro, (key, fmt) in M.items():
        if key not in R:
            miss.append(key); continue
        out.append(f"\\newcommand{{\\{macro}}}{{{fmt.format(R[key])}}}")
    for s in SCHEMES:
        c = CAMEL[s]
        for stat, fmt, pre in (("lo", "{:+.2f}", "Lo"), ("hi", "{:+.2f}", "Hi"),
                               ("worst", "{:+.2f}", "Worst"),
                               ("severe_pct", "{:.1f}", "Sev"),
                               ("n", "{:.0f}", "N")):
            k = f"{stat}::{s}"
            if k in R:
                out.append(f"\\newcommand{{\\{pre}{c}}}{{{fmt.format(R[k])}}}")
            else:
                miss.append(k)
    for p in PRED:
        k = f"pred_mae::{p}"
        if k in R:
            out.append(f"\\newcommand{{\\Mae{PCAMEL[p]}}}{{{R[k]:.4f}}}")
        else:
            miss.append(k)
    for cell, mac in (("w4a16|<2B", "CellWfourSmall"),
                      ("w8a16|>10B", "CellWsixteenBig")):
        for pre, key, fmt in (("Cov", "cell_coverage_pct", "{:.1f}"),
                              ("Rows", "cell_rows", "{:.0f}")):
            k = f"{key}::{cell}"
            if k in R:
                out.append(f"\\newcommand{{\\{pre}{mac}}}{{{fmt.format(R[k])}}}")
            else:
                miss.append(k)
    if miss:
        raise SystemExit("missing registry keys: " + ", ".join(sorted(set(miss))))
    names = re.findall(r"\\newcommand\{\\(\w+)\}", "\n".join(out))
    dupes = sorted({n for n in names if names.count(n) > 1})
    if dupes:
        raise SystemExit("duplicate macro definitions (LaTeX will refuse): "
                         + ", ".join(dupes))
    p = os.path.join(HERE, "numbers.tex")
    open(p, "w").write("\n".join(out) + "\n")
    print(f"wrote {p}: {len([l for l in out if l.startswith(chr(92)+'newcommand')])} macros")
    return 0


if __name__ == "__main__":
    sys.exit(main())
